version: '3'
services:
  frontend:
    build: .
    image: acs-frontend
    container_name: acs-frontend
    stdin_open: true
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - ./:/var/www/html/acs-frontend
